### ISSUE TITLE
I can view and use the app across phone and desktop

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/curenetics#33]
The design will be desktop first, with a single breakpoint to make look suitable for phones/tablets

Acceptance criteria:

- [ ] Functional on browsers outlined in #32 
- [ ] Functional on default browser on mobile devices
- [ ] 1 break point between desktop and phone, to provide some responsiveness to the web app
